---
- name: Update stamp file
  ansible.builtin.template:
    src: "{{ stamp_file_template }}"
    dest: "{{ stamp_file_path }}"
    owner: "root"
    group: "root"
    mode: "u=rw,g=r,o=r"
  when: stamp_file_contents != ""
  changed_when: false
