---
- name: Converge
  hosts: all
  tasks:
    - name: "Include wandansible.stamp"
      ansible.builtin.include_role:
        name: "wandansible.stamp"
      vars:
        stamp_motd_contents: |2+

            Host: {{ ansible_facts.fqdn }}
              OS: {{ ansible_facts.lsb.description }}
